server:
  port: 8080
  servlet:
    context-path: /boot
  
# =====================数据源配置===========================
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/credit?characterEncoding=utf8
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
# =====================Thymeleaf 配置===========================
  thymeleaf:
    enabled: true  # 是否启用thymeleaf模板解析
    cache: false   # 是否开启模板缓存（建议：开发环境下设置为false，生产环境设置为true）
    check-template-location: true # Check that the templates location exists.
    servlet: 
      content-type: text/html  # 模板的媒体类型设置，默认为text/html
    encoding: UTF-8  # 模板的编码设置，默认UTF-8
    characterEncoding: UTF-8
    #view-names:  # 设置可以被解析的视图，以逗号,分隔
    #excluded-view-names: # 排除不需要被解析视图，以逗号,分隔
    #mode:HTML5 # 模板模式设置，默认为HTML5
    prefix: classpath:/templates/  # 前缀设置，SpringBoot默认模板放置在classpath:/template/目录下
    suffix: .html  # 后缀设置，默认为.html
    #template-resolver-order: # 模板在模板链中被解析的顺序
  jmx:
#    enabled: false
    default-domain: springboottest   
logging:
  path: D:\JavaFiles\logs\spring boot\logs
  level: 
        com.springboottest.dao: DEBUG
